// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_fix_admin_passord_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_fix_admin_passord_length));
        
        string IMigrationMetadata.Id
        {
            get { return "202508251211097_mig_fix_admin_passord_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
