// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_heaing_status_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_heaing_status_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202508211418342_mig_heaing_status_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
